#version: "0.1"
services:
  mc:
    build: .
#      context: .
#      dockerfile: Dockerfile
#      target: final
    ports:
      - "25565:25565"
    container_name: mc
    networks:
      - custom-network

  ngrok:
    build: ./web/
    environment:
      - NGROK_AUTH=2LAl4T2DSH9FJQO6G4WQxMzIPhp_7tbNArk2az8LWTqPryuf5
      - NGROK_PROTOCOL=TCP
      - NGROK_PORT=25565
#    ports:
#      - "25565:25565"
    depends_on:
      - "mc"
    container_name: ngrok
    networks:
      - custom-network

networks:
  custom-network:
    name: custom-network

